import localFont from "next/font/local";
import Head from "next/head";
import "./globals.css";
import { Aleo, Climate_Crisis } from 'next/font/google';
import Navbar from "./components/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
    
const climateCrisis = Climate_Crisis({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-climate-crisis',
  weight: ['400']
});
    
const aleo = Aleo({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-aleo-serif',
  weight: ['100','200','300','400','500','600','700','800','900']
});

export const metadata = {
  title: "MyRecipeBook",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link rel="preconnect" as="stylesheet" href="https://fonts.googleapis.com/css2?family=Climate+Crisis&display=swap" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Aleo:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Azeret+Mono:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet" />
      </Head>
      <body className={`${climateCrisis.className}, ${aleo.className}`}>
        {children}
      </body>
    </html>
  );
}
